import logging
import os
from typing import Any

import boto3


LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)

SNS = boto3.client("sns")


def lambda_handler(event: dict[str, Any], _context: Any) -> dict[str, Any]:
    """
    Simplified prepare merge function that just sends a notification.

    Instead of automatically creating GitHub PRs (which requires a PAT),
    this function notifies the team that a new upstream release is available
    and they should manually sync the fork when convenient.

    This is a safer approach for an internship project that doesn't require
    personal GitHub tokens.
    """
    LOGGER.info("Processing upstream release notification: %s", event)

    upstream_version = event.get("upstream_version")
    if not upstream_version:
        raise ValueError("upstream_version is required")

    # Get configuration from environment
    fork_repo = os.environ["FORK_REPO"]
    upstream_owner = os.environ["UPSTREAM_OWNER"]
    upstream_repo = os.environ["UPSTREAM_REPO"]
    sns_topic_arn = os.environ["SNS_TOPIC_ARN"]
    release_url = event.get("release_url", "N/A")
    release_notes = event.get("release_notes", "No release notes available")

    LOGGER.info(
        "New upstream release detected: %s/%s version %s",
        upstream_owner,
        upstream_repo,
        upstream_version,
    )

    # Send notification to SNS topic
    notification_subject = f"🔔 New Upstream Release: {upstream_version}"

    notification_message = f"""
New Upstream Release Detected
==============================

Upstream Repository: {upstream_owner}/{upstream_repo}
Your Fork: {fork_repo}
New Version: {upstream_version}
Release URL: {release_url}

Release Notes:
{release_notes[:500]}{'...' if len(release_notes) > 500 else ''}

Action Required:
----------------
Please manually sync the fork repository when convenient:
1. Go to https://github.com/{fork_repo}
2. Click "Sync fork" button
3. Review changes and merge when ready

This notification was generated by the Fork-Update Agent.
The agent has detected that the upstream repository has a new release,
but manual review and merge is required for security and quality control.

---
🤖 Fork-Update Agent
"""

    try:
        SNS.publish(
            TopicArn=sns_topic_arn,
            Subject=notification_subject,
            Message=notification_message,
        )
        LOGGER.info("Notification sent successfully to SNS topic: %s", sns_topic_arn)
    except Exception as err:
        LOGGER.error("Failed to send SNS notification: %s", err, exc_info=True)
        # Don't fail the entire workflow if notification fails
        # Just log it and continue

    # Return information about the detected release
    # This allows the workflow to continue to deployment if configured
    return {
        "upstream_version": upstream_version,
        "fork_repo": fork_repo,
        "release_url": release_url,
        "notification_sent": True,
        "merge_status": "notification_sent",
        "message": f"Notification sent about upstream version {upstream_version}. Manual merge required.",
        "pr_url": f"https://github.com/{fork_repo}",  # Link to fork repo for manual sync
    }
